/*
Live Package Manager, Package Manager for LBLive
Copyright (C) <2015>  <xy12423>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#pragma once

#ifndef _H_LANG
#define _H_LANG

enum msgID{
	MSGI_SRCINFO_REFING,
	MSGI_SRCINFO_REFED,
	MSGI_DECOMPRESSING,
	MSGI_DECOMPRESSED,
	MSGI_COPYING,
	MSGI_COPIED,
	MSGI_DELETING,
	MSGI_DELETED,
	MSGI_PAK_SEARCHING,
	MSGI_PAK_FOUND,
	MSGI_PAK_INSTALLING,
	MSGI_PAK_INSTALLED,
	MSGI_PAKS_INSTALLED,
	MSGI_PAK_REMOVING,
	MSGI_PAK_REMOVED,
	MSGI_PAK_UPGRADING,
	MSGI_PAK_REINSTALLING,
	MSGI_RUNS_INST,
	MSGI_RUNS_INIT,
	MSGI_RUNS_PURGE,
	MSGI_RUNS_REMOVE,
	MSGI_DONE,
	MSGI_CHECK_REQUIREMENT,
	MSGI_WILL_DO_LIST,
	MSGI_WILL_REMOVE_LIST,
	MSGI_CONNECTING,
	MSGI_DOWNLOADING,
	MSGI_DOWNLOADED,
	MSGI_BACKUPING,
	MSGI_BACKUPED,
	MSGI_RECOVERING,
	MSGI_RECOVERED,
	MSGI_UPGRADE,
	MSGI_NO_UPGRADE,
	MSGI_PAK_NOT_FOUND_SPEC_1,
	MSGI_PAK_NOT_FOUND_SPEC_2,
	MSGI_TRACE_INFO,
	MSGI_USING_LPMDIR,
	MSGI_USING_LOCAL,

	MSGE_SRCINFO,
	MSGE_RUNS,
	MSGE_OVERWRITE,
	MSGE_ILLEGAL_PAK,
	MSGE_CONF,
	MSGE_DEP,
	MSGE_DEP_CONF,
	MSGE_PAK_NOT_FOUND,
	MSGE_PAK_NOT_FOUND_SPEC,
	MSGE_PAK_INSTALLED,
	MSGE_PAK_NOT_INSTALLED,
	MSGE_PAK_LATEST,
	MSGE_PAK_BE_DEP,
	MSGE_PAK_DEPINFO_NOT_FOUND,
	MSGE_BACKUP_EXISTS,
	MSGE_RECOVER_NOT_FOUND,
	MSGE_FS,
	MSGE_NETWORK,
	MSGE_UNZIP_BROKEN,
	MSGE_UNZIP_INFLATEINIT,
	MSGE_UNZIP_INFLATE,
	MSGE_UNZIP_INFLATEEND,
	MSGE_UNZIP_MEM_OVERFLOW,
	MSGE_UNZIP_BUF_OVERFLOW,
	MSGE_STD,
	MSGE_LOCK,
	MSGE_NO_CONFIG,

	MSGW_CONF,
	MSGW_RUNS_ROLL_BACK_1,
	MSGW_RUNS_ROLL_BACK_2,
	MSGW_PAK_BE_DEP,

	MSGN_INST,
	MSGN_UPG,
	MSGN_REMOVE,

	msgCount
};

#endif
